.github/CODEOWNERS, .github/dependabot.yml, .github/workflows/enarxbot.yml, .github/workflows/lint.yml, .github/workflows/test.yml, Cargo.toml, README.md
Also update Cargo.toml and README.md according to enarx standards.
=> ci: add github actions

src/syscall/mod.rs
=> fix: cfg on if expression

src/lib.rs, src/syscall/enarx.rs, src/syscall/mod.rs
=> feat: add missing bits for kvm loader - shim communication

.github/workflows/test.yml, Cargo.toml, src/lib.rs, src/tests.rs
Merge this first: https://github.com/enarx/primordial/pull/10
=> Bump primordial dependency

src/lib.rs
The shims can put `REQUIRES` in a note. Then the keepldr can evaluate
`REQUIRES` against `VERSION`.
Signed-off-by: Nathaniel McCallum <nathaniel@profian.com>
=> Switch to using semver semantics for versioning

src/elf.rs, src/lib.rs
Also, expand the constants for new SGX types.
=> Move ELF constants into their own module

.github/CODEOWNERS
Signed-off-by: Nathaniel McCallum <nathaniel@profian.com>
=> Add npmccallum to CODEOWNERS

src/v2/src/guest/alloc/inout.rs, src/v2/src/guest/alloc/input.rs, src/v2/src/guest/alloc/mod.rs, src/v2/src/guest/alloc/output.rs, src/v2/src/guest/alloc/phase_alloc.rs, src/v2/src/guest/alloc/syscall.rs, src/v2/src/guest/alloc/tests.rs, src/v2/src/guest/mod.rs, src/v2/src/guest/syscall/argv.rs, src/v2/src/guest/syscall/exit.rs, src/v2/src/guest/syscall/mod.rs, src/v2/src/guest/syscall/result/linux/mod.rs, src/v2/src/guest/syscall/result/linux/x86_64.rs, src/v2/src/guest/syscall/result/mod.rs, src/v2/src/guest/syscall/tests.rs, src/v2/src/item/mod.rs, src/v2/src/lib.rs
Part of PR series for #17
Closes https://github.com/enarx/sallyport/issues/35
Blocked by ~https://github.com/enarx/sallyport/pull/28~ ~#27 (due to `item` crate changes)~ #36
=> v2: Add guest allocator

src/v2/src/guest/alloc/syscall.rs, src/v2/src/guest/handler.rs, src/v2/src/guest/syscall/mod.rs, src/v2/src/guest/syscall/write.rs, src/v2/src/host/mod.rs, src/v2/src/host/syscall.rs, src/v2/tests/integration_tests.rs
Part of #34 
Blocking #41 
Including a few small commits here not directly related to the feature for speed of development, please review commit-by-commit.
=> Add support for `write` syscall

src/v2/src/guest/alloc/syscall.rs, src/v2/src/guest/handler.rs, src/v2/src/guest/syscall/close.rs, src/v2/src/guest/syscall/exit.rs, src/v2/src/guest/syscall/mod.rs, src/v2/src/guest/syscall/read.rs, src/v2/src/guest/syscall/result/linux/x86_64.rs, src/v2/src/guest/syscall/write.rs, src/v2/src/host/mod.rs, src/v2/src/host/syscall.rs, src/v2/tests/integration_tests.rs
Part of #34 
Blocked by ~#40~
Blocking #43 #47
=> Add support for `close` syscall

src/v2/src/guest/handler.rs, src/v2/src/guest/syscall/passthrough.rs, src/v2/src/host/syscall.rs
=> Add support for `exit_group` syscall

src/v2/src/guest/handler.rs, src/v2/src/guest/syscall/stub.rs
=> Add support for `uname` syscall

src/v2/src/guest/handler.rs, src/v2/src/guest/syscall/passthrough.rs, src/v2/src/host/syscall.rs
=> Add support for `dup{,2,3}` syscalls

src/v2/src/guest/alloc/mod.rs, src/v2/src/guest/handler.rs, src/v2/src/guest/syscall/accept.rs, src/v2/src/guest/syscall/accept4.rs, src/v2/src/guest/syscall/bind.rs, src/v2/src/guest/syscall/connect.rs, src/v2/src/guest/syscall/mod.rs, src/v2/src/guest/syscall/types.rs, src/v2/src/host/syscall.rs
Closes #61 
Part of #34 
~This includes the `NULL` commit for #47~
=> Add support for `accept{,4}`

src/syscall/file.rs
This is needed for mio running on wasi.
=> feat: add `FIONREAD` ioctl

src/guest/call/mod.rs, src/guest/handler.rs
fix: correct the `brk` signature
fix: make kind public
=> fix: some sallyport issues

src/guest/call/mod.rs, src/guest/handler.rs, src/guest/platform.rs, tests/integration_tests.rs
=> feat(guest): turn `Handler` into a trait

src/host/enarxcall.rs, src/host/mod.rs, src/host/syscall.rs, tests/integration_tests/mod.rs
Refs discussion on https://github.com/enarx/enarx/pull/1460
=> fix(host): propagate `host::execute` errors to the caller

src/guest/call/syscall/setsockopt.rs, tests/integration_tests/syscall.rs
Make sure `optval` is actually written to the block
=> fix(guest): commit `setsockopt` optval

src/guest/call/syscall/fcntl.rs, src/guest/call/syscall/ioctl.rs, src/guest/call/syscall/open.rs, src/guest/handler.rs
Refactor `MaybeAlloc` call organization, implement the trait for `Ioctl` for better organization and consistency
=> fix(guest): implement `MaybeAlloc` for `Ioctl`
