src/syscall/file.rs
The block comment confused `cargo fmt`.
=> fix: fstat debug trace comment

.github/workflows/test.yml, Cargo.toml, src/lib.rs, src/tests.rs
For non-nightly code to use sallyport.
=> fix: guard asm code behind asm feauture

src/syscall/mod.rs
```
error: returning the result of a `let` binding from a block
--> src/syscall/mod.rs:305:9
|
175 | /         let ret = match nr as _ {
176 | |             // MemorySyscallHandler
177 | |             libc::SYS_brk => self.brk(a.into()),
178 | |             libc::SYS_mmap => self.mmap(
...   |
302 | |             }
303 | |         };
| |__________- unnecessary `let` binding
304 |
305 |           ret
|           ^^^
|
```
=> fix: clippy error: returning the result of a `let` binding from a block

src/syscall/mod.rs
```
--> src/syscall/mod.rs:28:9
|
28 | /// See https://github.com/enarx/enarx-keepldr/issues/31
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use an automatic link instead: `<https://github.com/enarx/enarx-keepldr/issues/31>`
|
= note: `#[warn(rustdoc::bare_urls)]` on by default
= note: bare URLs are not automatically turned into clickable links
```
=> fix: warning: this URL is not a hyperlink

src/elf.rs
Shims can support multiple backends. So this doesn't make sense.
=> Drop the `BACKEND` note

src/elf.rs
For the new enarx keep loader, using flags instead of types suits better
for some PT_LOAD segments.
=> feat: use programm header flags instead of types

src/syscall/enarx.rs, src/syscall/mod.rs
To enable gdb debugging specialized functions are needed.
Instead of using the normal syscalls, we use these, so that any filter
mechanisms do not have to make exceptions for the gdb connection.
=> feat: add Enarx gdb extensions

src/lib.rs
`asm` is now stable on nightly.
=> fix: remove asm feature

.github/workflows/test.yml
Drop support for 1.57.0 and `stable` toolchains
=> Drop support for 1.57.0 and `stable` toolchains

.github/workflows/test.yml
- Run `cargo miri test` on CI
- Test both crate versions present in the repo (currently, only v1 tests are run)
- Simplify test matrix
=> Run miri test on CI, test both crate versions

src/v2/src/guest/alloc/mod.rs, src/v2/src/guest/handler.rs, src/v2/src/guest/syscall/mod.rs, src/v2/src/guest/syscall/sync.rs, src/v2/src/host/mod.rs, src/v2/src/host/syscall.rs, src/v2/tests/integration_tests.rs
Part of #34 
The tuple trait implementations are used for syscall implementations and, as a side effect, enable batching by design, which is utilized in the test
=> Add support for `sync` syscall

src/v2/src/guest/handler.rs
- Avoid leaking implementation details from the trait and simplify extensibility (e.g. for #65)
- Somewhere along the road lexicographic ordering of syscall methods was broken - fixed that
=> v2 guest `Execute` trait usability improvements

src/v2/Cargo.toml, src/v2/src/guest/alloc/inout.rs, src/v2/src/guest/alloc/input.rs, src/v2/src/guest/alloc/mod.rs, src/v2/src/guest/alloc/output.rs, src/v2/src/guest/alloc/phase_alloc.rs, src/v2/src/guest/handler.rs, src/v2/src/host/mod.rs
#47 sans the actual syscall, for which NULL handling is still to be discussed
blocking #67 #47 (since the dependencies of the implementation are now extracted here)
=> Guest allocator `inout` support and a few minor fixes/improvements

src/v2/src/guest/handler.rs
Part of #34 
Just like https://github.com/enarx/sallyport/blob/8efea8f02f46af32f570ddac6b6a86bd51755733/src/syscall/memory.rs#L8-L37
This is mostly just the signatures and `syscall` method matching.
It is expected that users of this crate requiring these syscalls will create a custom `Handler`, which will `impl Execute` and provide implementations for these methods.
Note, that if that would require proxying the (custom) syscall to the host, then currently we have no mechanism in place to cater for that, but that would be easy to implement - please let me know if we need that now and/or file a follow-up issue.
=> Add support for memory-related syscalls

src/v2/src/guest/handler.rs, src/v2/src/guest/platform.rs, src/v2/src/guest/syscall/mod.rs, src/v2/src/guest/syscall/readv.rs, src/v2/src/guest/syscall/writev.rs, src/v2/tests/integration_tests.rs
Part of #34 
Closes #50 
Closes #60 
Still TODO:
=> Add support for `{read,write}v` syscalls

src/syscall/file.rs, src/syscall/mod.rs, src/v2/src/guest/call/syscall/ioctl.rs, src/v2/src/guest/handler.rs
Apparently `x86_64-unknown-linux-musl` and `x86_64-unknown-linux-gnu`
differ now in this type.
Fixes: #86
=> fix: use `libc::Ioctl` instead of `c_ulong`

src/guest/alloc/phase_alloc.rs, src/guest/handler.rs, tests/integration_tests.rs
In order to allow for sound implementations of `Handler` trait, allow
releasing the ownership of underlying block in `Commit` phase by the
allocator.
=> feat(guest): release the ownership of the block on sally

src/elf.rs
Add two elf note tags, which report about the shim's sallyport block
size and the number of blocks.
=> feat: add elf notes with block info

src/guest/call/syscall/stub.rs, src/guest/handler.rs
=> fix(sigaltstack): first argument can be NULL

src/guest/handler.rs, src/guest/platform.rs, src/lib.rs, src/util/mod.rs, src/util/ptr.rs, tests/integration_tests/enarxcall.rs, tests/integration_tests/mod.rs, tests/integration_tests/syscall.rs
Previously the `validate_*` methods were giving out objects with an
unbound lifetime.
To ensure lifetimes don't outlive the real syscall, the caller of
`Handler::syscall` now has to pass a `Platform` object, which binds the
lifetimes of all objects generated by its `validate_*` methods to
itsself.
Also the `sally()` method is now part of the `Handler` trait to decouple
it from the `Platform` object, because it needs a mutable self.
The implementation of the `Platform` object has to use internal
mutablity to be able to hand out multiple mutable references.
To be feature complete, the `Platform` trait would have to have `drop`
methods for its internal bookkeeping. But doing so is a out of scope for
this project for now.
=> fix: separate memory validation from Handler

src/guest/call/syscall/stub.rs
Remove the `flags` variable to not confuse it with `self.flags`, as it
is only needed to check for the validity of `self.flags`.
Related: https://github.com/enarx/sallyport/issues/116
=> fix: avoid confusion with getrandom flags

src/guest/call/enarxcall/passthrough.rs, src/guest/handler.rs, src/item/enarxcall/mod.rs, src/item/enarxcall/sgx.rs, tests/integration_tests/enarxcall.rs
The SGX quote size is not a constant.
Remove any SGX constants and introduce a new enarx sallyport call to get
the quote size.
Related: https://github.com/enarx/enarx/issues/1534
=> feat: add get_sgx_quote_size() enarx call

Cargo.toml, src/guest/call/syscall/types/result/linux/x86_64.rs, src/libc.rs, tests/integration_tests/syscall.rs
Refs #126 
I still think we should rely on upstream `libc` in tests completely to test e.g. the validity of duplicated constants on particular platform the test is run on.
cc @rjzak
=> fix: remove `libc` function bindings

src/guest/call/syscall/tests.rs, src/guest/call/syscall/types/result/linux/x86_64.rs, src/host/mod.rs, src/item/block.rs, tests/integration_tests/enarxcall.rs, tests/integration_tests/mod.rs, tests/integration_tests/syscall.rs
Trying to close #126. There are some unchanged tests which didn't use the internal libc for constants.
Signed-off-by: Richard Zak <richard@profian.com>
=> test: use `libc` constants in tests for #126

src/guest/handler.rs, tests/integration_tests/mod.rs, tests/integration_tests/syscall.rs
A simple fallback implementation, which just unmaps or copies over data
to a newly mapped region.
=> feat: default mremap() implementation

Cargo.toml
Avoid specifying point releases to at least use the latest version within minor
=> build(deps): use latest versions within minor

tests/integration_tests/syscall.rs
Eliminate clippy warning on test with miri
=> test: eliminate clippy warnings when miri is used
